#pragma once
#include"function.h"
#include"ErrCode.h"
#include"Sales_data.h"
#include"Person.h"
#include"Screen2.h"
#include"static.h"
#include"XY.h"
#include"Exercise.h"
#include"streamProcess.h"
#include"connection.h"
#include"TextQuery.h"
#include"StrBlob.h"
#include"numbered.h"
#include"default_test.h"
#include"Employee.h"
#include"HasPtr.h"
#include"message.h"
#include"Forder.h"
#include "MyString.h"
#include "stringVec.h"
#include "Foo.h"
#include "operatorFun.h"
#include "ClassConversion.h"